node[name="{{name}}"][railway~"^(stop|halt|station)$"]->.stop;
( way[railway=platform](around.stop:100)[bus!~yes];
  way[public_transport=platform](around.stop:100)[bus!~yes];
  rel[railway=platform](around.stop:100)[bus!~yes];
  rel[public_transport=platform](around.stop:100)[bus!~yes];
  way[railway=platform][name="{{name}}"];
  rel[railway=platform][name="{{name}}"]; );
(._;node[highway](around:100)->.n;way[highway](around:100););
(._;>;);
out geom;
